### ISSUE TITLE
home.html 개발

### ISSUE THREAD

**Issue by Gjunghoon** [Gjunghoon/gugudog#12]
base.html
- [ ] navbar
- [ ] bottom bar

home.html
- [ ] 이번달 결제 금액 총액_header
- [ ] 각각 구독 서비스 나타내는 div
- [ ] Add 버튼
- [ ] 이번달  구독 포인트_header
- [ ] 구독 포인트 나타내는 div
- [ ] 좌우 이동 버튼

**Comment by SeeunChoi1** [comment]
![image](https://user-images.githubusercontent.com/37589355/61930582-24a34080-afb9-11e9-9ad8-991bd5d1ba08.png)
